


	select 

	`x`.`id` AS `id`,`x`.`group_id`

	 from 


	(((((((((`hrone`.`working_schedule_01`))) 



	union 



	select `hrone`.`working_schedule_02`.`id` AS `employee_id`,`hrone`.`working_schedule_02`.`shift_id` AS `shift_id`,`hrone`.`working_schedule_02`.`date` AS `date`,`hrone`.`working_schedule_02`.`company_id` AS `company_id`,`hrone`.`working_schedule_02`.`employee_id` AS `employee_id`,`hrone`.`working_schedule_02`.`mm` AS `mm`,`hrone`.`working_schedule_02`.`yy` AS `yy`,`hrone`.`working_schedule_02`.`dd` AS `dd`,`hrone`.`working_schedule_02`.`shift_category` AS `shift_category`,`hrone`.`working_schedule_02`.`shift_in` AS `shift_in`,`hrone`.`working_schedule_02`.`shift_out` AS `shift_out`,`hrone`.`working_schedule_02`.`time_in` AS `time_in`,`hrone`.`working_schedule_02`.`time_out` AS `time_out`,`hrone`.`working_schedule_02`.`plotter` AS `plotter`,`hrone`.`working_schedule_02`.`date_plotted` AS `date_plotted`,`hrone`.`working_schedule_02`.`restday` AS `restday`,`hrone`.`working_schedule_02`.`group_id` AS `group_id`,`hrone`.`employee_info`.`first_name` AS `first_name`,`hrone`.`employee_info`.`middle_name` AS `middle_name`,`hrone`.`employee_info`.`last_name` AS `last_name`,`hrone`.`employee_info`.`InActive` AS `InActive`,`hrone`.`company_info`.`company_name` AS `company_name`,`hrone`.`division`.`division_name` AS `division_name`,`hrone`.`department`.`dept_name` AS `dept_name`,`hrone`.`section`.`section_name` AS `section_name`,`hrone`.`subsection`.`subsection_name` AS `subsection_name`,`hrone`.`classification`.`classification` AS `classification`,`hrone`.`location`.`location_name` AS `location_name`,`hrone`.`employment`.`employment_name` AS `employment_name`,`hrone`.`employment`.`employment_id` AS `employment_id`,`hrone`.`division`.`division_id` AS `division_id`,`hrone`.`department`.`department_id` AS `department_id`,`hrone`.`section`.`section_id` AS `section_id`,`hrone`.`subsection`.`subsection_id` AS `subsection_id`,`hrone`.`classification`.`classification_id` AS `classification_id`,`hrone`.`location`.`location_id` AS `location_id` from (((((((((`hrone`.`working_schedule_02` join `hrone`.`employee_info` on((`hrone`.`employee_info`.`employee_id` = `hrone`.`working_schedule_02`.`employee_id`))) join `hrone`.`employment` on((`hrone`.`employment`.`employment_id` = `hrone`.`employee_info`.`employment`))) join `hrone`.`company_info` on((`hrone`.`company_info`.`company_id` = `hrone`.`employee_info`.`company_id`))) join `hrone`.`division` on((`hrone`.`division`.`division_id` = `hrone`.`employee_info`.`division_id`))) join `hrone`.`department` on((`hrone`.`department`.`department_id` = `hrone`.`employee_info`.`department`))) join `hrone`.`section` on((`hrone`.`section`.`section_id` = `hrone`.`employee_info`.`section`))) join `hrone`.`subsection` on((`hrone`.`subsection`.`subsection_id` = `hrone`.`employee_info`.`subsection`))) join `hrone`.`classification` on((`hrone`.`classification`.`classification_id` = `hrone`.`employee_info`.`classification`))) join `hrone`.`location` on((`hrone`.`location`.`location_id` = `hrone`.`employee_info`.`location`))) 




	union 




	select 

			`hrone`.`working_schedule_03`.`id` AS `id`,
			`hrone`.`working_schedule_03`.`shift_id` AS `shift_id`,
			`hrone`.`working_schedule_03`.`date` AS `date`,
			`hrone`.`working_schedule_03`.`company_id` AS `company_id`,
			`hrone`.`working_schedule_03`.`employee_id` AS `employee_id`,
			`hrone`.`working_schedule_03`.`mm` AS `mm`,
			`hrone`.`working_schedule_03`.`yy` AS `yy`,
			`hrone`.`working_schedule_03`.`dd` AS `dd`,
			`hrone`.`working_schedule_03`.`shift_category` AS `shift_category`,
			`hrone`.`working_schedule_03`.`shift_in` AS `shift_in`,
			`hrone`.`working_schedule_03`.`shift_out` AS `shift_out`,
			`hrone`.`working_schedule_03`.`time_in` AS `time_in`,
			`hrone`.`working_schedule_03`.`time_out` AS `time_out`,
			`hrone`.`working_schedule_03`.`plotter` AS `plotter`,
			`hrone`.`working_schedule_03`.`date_plotted` AS `date_plotted`,
			`hrone`.`working_schedule_03`.`restday` AS `restday`,
			`hrone`.`working_schedule_03`.`group_id` AS `group_id`,
			`hrone`.`employee_info`.`first_name` AS `first_name`,
			`hrone`.`employee_info`.`middle_name` AS `middle_name`,
			`hrone`.`employee_info`.`last_name` AS `last_name`,
			`hrone`.`employee_info`.`InActive` AS `InActive`,
			`hrone`.`company_info`.`company_name` AS `company_name`,
			`hrone`.`division`.`division_name` AS `division_name`,
			`hrone`.`department`.`dept_name` AS `dept_name`,
			`hrone`.`section`.`section_name` AS `section_name`,
			`hrone`.`subsection`.`subsection_name` AS `subsection_name`,
			`hrone`.`classification`.`classification` AS `classification`,
			`hrone`.`location`.`location_name` AS `location_name`,
			`hrone`.`employment`.`employment_name` AS `employment_name`,
			`hrone`.`employment`.`employment_id` AS `employment_id`,
			`hrone`.`division`.`division_id` AS `division_id`,
			`hrone`.`department`.`department_id` AS `department_id`,
			`hrone`.`section`.`section_id` AS `section_id`,
			`hrone`.`subsection`.`subsection_id` AS `subsection_id`,
			`hrone`.`classification`.`classification_id` AS `classification_id`,
			`hrone`.`location`.`location_id` AS `location_id` 
			
			from (((((((((`hrone`.`working_schedule_03` 
			join `hrone`.`employee_info` on((`hrone`.`employee_info`.`employee_id` = `hrone`.`working_schedule_03`.`employee_id`))) 
			join `hrone`.`employment` on((`hrone`.`employment`.`employment_id` = `hrone`.`employee_info`.`employment`))) 
			join `hrone`.`company_info` on((`hrone`.`company_info`.`company_id` = `hrone`.`employee_info`.`company_id`))) join `hrone`.`division` on((`hrone`.`division`.`division_id` = `hrone`.`employee_info`.`division_id`))) 
			join `hrone`.`department` on((`hrone`.`department`.`department_id` = `hrone`.`employee_info`.`department`))) 
			join `hrone`.`section` on((`hrone`.`section`.`section_id` = `hrone`.`employee_info`.`section`))) 
			join `hrone`.`subsection` on((`hrone`.`subsection`.`subsection_id` = `hrone`.`employee_info`.`subsection`))) 
			join `hrone`.`classification` on((`hrone`.`classification`.`classification_id` = `hrone`.`employee_info`.`classification`))) 
			join `hrone`.`location` on((`hrone`.`location`.`location_id` = `hrone`.`employee_info`.`location`))) 



	union 


	select `hrone`.`working_schedule_04`.`id` AS `id`,`hrone`.`working_schedule_04`.`shift_id` AS `shift_id`,`hrone`.`working_schedule_04`.`date` AS `date`,`hrone`.`working_schedule_04`.`company_id` AS `company_id`,`hrone`.`working_schedule_04`.`employee_id` AS `employee_id`,`hrone`.`working_schedule_04`.`mm` AS `mm`,`hrone`.`working_schedule_04`.`yy` AS `yy`,`hrone`.`working_schedule_04`.`dd` AS `dd`,`hrone`.`working_schedule_04`.`shift_category` AS `shift_category`,`hrone`.`working_schedule_04`.`shift_in` AS `shift_in`,`hrone`.`working_schedule_04`.`shift_out` AS `shift_out`,`hrone`.`working_schedule_04`.`time_in` AS `time_in`,`hrone`.`working_schedule_04`.`time_out` AS `time_out`,`hrone`.`working_schedule_04`.`plotter` AS `plotter`,`hrone`.`working_schedule_04`.`date_plotted` AS `date_plotted`,`hrone`.`working_schedule_04`.`restday` AS `restday`,`hrone`.`working_schedule_04`.`group_id` AS `group_id`,`hrone`.`employee_info`.`first_name` AS `first_name`,`hrone`.`employee_info`.`middle_name` AS `middle_name`,`hrone`.`employee_info`.`last_name` AS `last_name`,`hrone`.`employee_info`.`InActive` AS `InActive`,`hrone`.`company_info`.`company_name` AS `company_name`,`hrone`.`division`.`division_name` AS `division_name`,`hrone`.`department`.`dept_name` AS `dept_name`,`hrone`.`section`.`section_name` AS `section_name`,`hrone`.`subsection`.`subsection_name` AS `subsection_name`,`hrone`.`classification`.`classification` AS `classification`,`hrone`.`location`.`location_name` AS `location_name`,`hrone`.`employment`.`employment_name` AS `employment_name`,`hrone`.`employment`.`employment_id` AS `employment_id`,`hrone`.`division`.`division_id` AS `division_id`,`hrone`.`department`.`department_id` AS `department_id`,`hrone`.`section`.`section_id` AS `section_id`,`hrone`.`subsection`.`subsection_id` AS `subsection_id`,`hrone`.`classification`.`classification_id` AS `classification_id`,`hrone`.`location`.`location_id` AS `location_id` from (((((((((`hrone`.`working_schedule_04` join `hrone`.`employee_info` on((`hrone`.`employee_info`.`employee_id` = `hrone`.`working_schedule_04`.`employee_id`))) join `hrone`.`employment` on((`hrone`.`employment`.`employment_id` = `hrone`.`employee_info`.`employment`))) join `hrone`.`company_info` on((`hrone`.`company_info`.`company_id` = `hrone`.`employee_info`.`company_id`))) join `hrone`.`division` on((`hrone`.`division`.`division_id` = `hrone`.`employee_info`.`division_id`))) join `hrone`.`department` on((`hrone`.`department`.`department_id` = `hrone`.`employee_info`.`department`))) join `hrone`.`section` on((`hrone`.`section`.`section_id` = `hrone`.`employee_info`.`section`))) join `hrone`.`subsection` on((`hrone`.`subsection`.`subsection_id` = `hrone`.`employee_info`.`subsection`))) join `hrone`.`classification` on((`hrone`.`classification`.`classification_id` = `hrone`.`employee_info`.`classification`))) join `hrone`.`location` on((`hrone`.`location`.`location_id` = `hrone`.`employee_info`.`location`))) 







	union 


	select `hrone`.`working_schedule_05`.`id` AS `id`,`hrone`.`working_schedule_05`.`shift_id` AS `shift_id`,`hrone`.`working_schedule_05`.`date` AS `date`,`hrone`.`working_schedule_05`.`company_id` AS `company_id`,`hrone`.`working_schedule_05`.`employee_id` AS `employee_id`,`hrone`.`working_schedule_05`.`mm` AS `mm`,`hrone`.`working_schedule_05`.`yy` AS `yy`,`hrone`.`working_schedule_05`.`dd` AS `dd`,`hrone`.`working_schedule_05`.`shift_category` AS `shift_category`,`hrone`.`working_schedule_05`.`shift_in` AS `shift_in`,`hrone`.`working_schedule_05`.`shift_out` AS `shift_out`,`hrone`.`working_schedule_05`.`time_in` AS `time_in`,`hrone`.`working_schedule_05`.`time_out` AS `time_out`,`hrone`.`working_schedule_05`.`plotter` AS `plotter`,`hrone`.`working_schedule_05`.`date_plotted` AS `date_plotted`,`hrone`.`working_schedule_05`.`restday` AS `restday`,`hrone`.`working_schedule_05`.`group_id` AS `group_id`,`hrone`.`employee_info`.`first_name` AS `first_name`,`hrone`.`employee_info`.`middle_name` AS `middle_name`,`hrone`.`employee_info`.`last_name` AS `last_name`,`hrone`.`employee_info`.`InActive` AS `InActive`,`hrone`.`company_info`.`company_name` AS `company_name`,`hrone`.`division`.`division_name` AS `division_name`,`hrone`.`department`.`dept_name` AS `dept_name`,`hrone`.`section`.`section_name` AS `section_name`,`hrone`.`subsection`.`subsection_name` AS `subsection_name`,`hrone`.`classification`.`classification` AS `classification`,`hrone`.`location`.`location_name` AS `location_name`,`hrone`.`employment`.`employment_name` AS `employment_name`,`hrone`.`employment`.`employment_id` AS `employment_id`,`hrone`.`division`.`division_id` AS `division_id`,`hrone`.`department`.`department_id` AS `department_id`,`hrone`.`section`.`section_id` AS `section_id`,`hrone`.`subsection`.`subsection_id` AS `subsection_id`,`hrone`.`classification`.`classification_id` AS `classification_id`,`hrone`.`location`.`location_id` AS `location_id` from (((((((((`hrone`.`working_schedule_05` join `hrone`.`employee_info` on((`hrone`.`employee_info`.`employee_id` = `hrone`.`working_schedule_05`.`employee_id`))) join `hrone`.`employment` on((`hrone`.`employment`.`employment_id` = `hrone`.`employee_info`.`employment`))) join `hrone`.`company_info` on((`hrone`.`company_info`.`company_id` = `hrone`.`employee_info`.`company_id`))) join `hrone`.`division` on((`hrone`.`division`.`division_id` = `hrone`.`employee_info`.`division_id`))) join `hrone`.`department` on((`hrone`.`department`.`department_id` = `hrone`.`employee_info`.`department`))) join `hrone`.`section` on((`hrone`.`section`.`section_id` = `hrone`.`employee_info`.`section`))) join `hrone`.`subsection` on((`hrone`.`subsection`.`subsection_id` = `hrone`.`employee_info`.`subsection`))) join `hrone`.`classification` on((`hrone`.`classification`.`classification_id` = `hrone`.`employee_info`.`classification`))) join `hrone`.`location` on((`hrone`.`location`.`location_id` = `hrone`.`employee_info`.`location`))) 



	union





	 select `hrone`.`working_schedule_06`.`id` AS `id`,`hrone`.`working_schedule_06`.`shift_id` AS `shift_id`,`hrone`.`working_schedule_06`.`date` AS `date`,`hrone`.`working_schedule_06`.`company_id` AS `company_id`,`hrone`.`working_schedule_06`.`employee_id` AS `employee_id`,`hrone`.`working_schedule_06`.`mm` AS `mm`,`hrone`.`working_schedule_06`.`yy` AS `yy`,`hrone`.`working_schedule_06`.`dd` AS `dd`,`hrone`.`working_schedule_06`.`shift_category` AS `shift_category`,`hrone`.`working_schedule_06`.`shift_in` AS `shift_in`,`hrone`.`working_schedule_06`.`shift_out` AS `shift_out`,`hrone`.`working_schedule_06`.`time_in` AS `time_in`,`hrone`.`working_schedule_06`.`time_out` AS `time_out`,`hrone`.`working_schedule_06`.`plotter` AS `plotter`,`hrone`.`working_schedule_06`.`date_plotted` AS `date_plotted`,`hrone`.`working_schedule_06`.`restday` AS `restday`,`hrone`.`working_schedule_06`.`group_id` AS `group_id`,`hrone`.`employee_info`.`first_name` AS `first_name`,`hrone`.`employee_info`.`middle_name` AS `middle_name`,`hrone`.`employee_info`.`last_name` AS `last_name`,`hrone`.`employee_info`.`InActive` AS `InActive`,`hrone`.`company_info`.`company_name` AS `company_name`,`hrone`.`division`.`division_name` AS `division_name`,`hrone`.`department`.`dept_name` AS `dept_name`,`hrone`.`section`.`section_name` AS `section_name`,`hrone`.`subsection`.`subsection_name` AS `subsection_name`,`hrone`.`classification`.`classification` AS `classification`,`hrone`.`location`.`location_name` AS `location_name`,`hrone`.`employment`.`employment_name` AS `employment_name`,`hrone`.`employment`.`employment_id` AS `employment_id`,`hrone`.`division`.`division_id` AS `division_id`,`hrone`.`department`.`department_id` AS `department_id`,`hrone`.`section`.`section_id` AS `section_id`,`hrone`.`subsection`.`subsection_id` AS `subsection_id`,`hrone`.`classification`.`classification_id` AS `classification_id`,`hrone`.`location`.`location_id` AS `location_id` from (((((((((`hrone`.`working_schedule_06` join `hrone`.`employee_info` on((`hrone`.`employee_info`.`employee_id` = `hrone`.`working_schedule_06`.`employee_id`))) join `hrone`.`employment` on((`hrone`.`employment`.`employment_id` = `hrone`.`employee_info`.`employment`))) join `hrone`.`company_info` on((`hrone`.`company_info`.`company_id` = `hrone`.`employee_info`.`company_id`))) join `hrone`.`division` on((`hrone`.`division`.`division_id` = `hrone`.`employee_info`.`division_id`))) join `hrone`.`department` on((`hrone`.`department`.`department_id` = `hrone`.`employee_info`.`department`))) join `hrone`.`section` on((`hrone`.`section`.`section_id` = `hrone`.`employee_info`.`section`))) join `hrone`.`subsection` on((`hrone`.`subsection`.`subsection_id` = `hrone`.`employee_info`.`subsection`))) join `hrone`.`classification` on((`hrone`.`classification`.`classification_id` = `hrone`.`employee_info`.`classification`))) join `hrone`.`location` on((`hrone`.`location`.`location_id` = `hrone`.`employee_info`.`location`))) 




	 union 




	 select `hrone`.`working_schedule_07`.`id` AS `id`,`hrone`.`working_schedule_07`.`shift_id` AS `shift_id`,`hrone`.`working_schedule_07`.`date` AS `date`,`hrone`.`working_schedule_07`.`company_id` AS `company_id`,`hrone`.`working_schedule_07`.`employee_id` AS `employee_id`,`hrone`.`working_schedule_07`.`mm` AS `mm`,`hrone`.`working_schedule_07`.`yy` AS `yy`,`hrone`.`working_schedule_07`.`dd` AS `dd`,`hrone`.`working_schedule_07`.`shift_category` AS `shift_category`,`hrone`.`working_schedule_07`.`shift_in` AS `shift_in`,`hrone`.`working_schedule_07`.`shift_out` AS `shift_out`,`hrone`.`working_schedule_07`.`time_in` AS `time_in`,`hrone`.`working_schedule_07`.`time_out` AS `time_out`,`hrone`.`working_schedule_07`.`plotter` AS `plotter`,`hrone`.`working_schedule_07`.`date_plotted` AS `date_plotted`,`hrone`.`working_schedule_07`.`restday` AS `restday`,`hrone`.`working_schedule_07`.`group_id` AS `group_id`,`hrone`.`employee_info`.`first_name` AS `first_name`,`hrone`.`employee_info`.`middle_name` AS `middle_name`,`hrone`.`employee_info`.`last_name` AS `last_name`,`hrone`.`employee_info`.`InActive` AS `InActive`,`hrone`.`company_info`.`company_name` AS `company_name`,`hrone`.`division`.`division_name` AS `division_name`,`hrone`.`department`.`dept_name` AS `dept_name`,`hrone`.`section`.`section_name` AS `section_name`,`hrone`.`subsection`.`subsection_name` AS `subsection_name`,`hrone`.`classification`.`classification` AS `classification`,`hrone`.`location`.`location_name` AS `location_name`,`hrone`.`employment`.`employment_name` AS `employment_name`,`hrone`.`employment`.`employment_id` AS `employment_id`,`hrone`.`division`.`division_id` AS `division_id`,`hrone`.`department`.`department_id` AS `department_id`,`hrone`.`section`.`section_id` AS `section_id`,`hrone`.`subsection`.`subsection_id` AS `subsection_id`,`hrone`.`classification`.`classification_id` AS `classification_id`,`hrone`.`location`.`location_id` AS `location_id` from (((((((((`hrone`.`working_schedule_07` join `hrone`.`employee_info` on((`hrone`.`employee_info`.`employee_id` = `hrone`.`working_schedule_07`.`employee_id`))) join `hrone`.`employment` on((`hrone`.`employment`.`employment_id` = `hrone`.`employee_info`.`employment`))) join `hrone`.`company_info` on((`hrone`.`company_info`.`company_id` = `hrone`.`employee_info`.`company_id`))) join `hrone`.`division` on((`hrone`.`division`.`division_id` = `hrone`.`employee_info`.`division_id`))) join `hrone`.`department` on((`hrone`.`department`.`department_id` = `hrone`.`employee_info`.`department`))) join `hrone`.`section` on((`hrone`.`section`.`section_id` = `hrone`.`employee_info`.`section`))) join `hrone`.`subsection` on((`hrone`.`subsection`.`subsection_id` = `hrone`.`employee_info`.`subsection`))) join `hrone`.`classification` on((`hrone`.`classification`.`classification_id` = `hrone`.`employee_info`.`classification`))) join `hrone`.`location` on((`hrone`.`location`.`location_id` = `hrone`.`employee_info`.`location`))) 


	 union 





	 select `hrone`.`working_schedule_08`.`id` AS `id`,`hrone`.`working_schedule_08`.`shift_id` AS `shift_id`,`hrone`.`working_schedule_08`.`date` AS `date`,`hrone`.`working_schedule_08`.`company_id` AS `company_id`,`hrone`.`working_schedule_08`.`employee_id` AS `employee_id`,`hrone`.`working_schedule_08`.`mm` AS `mm`,`hrone`.`working_schedule_08`.`yy` AS `yy`,`hrone`.`working_schedule_08`.`dd` AS `dd`,`hrone`.`working_schedule_08`.`shift_category` AS `shift_category`,`hrone`.`working_schedule_08`.`shift_in` AS `shift_in`,`hrone`.`working_schedule_08`.`shift_out` AS `shift_out`,`hrone`.`working_schedule_08`.`time_in` AS `time_in`,`hrone`.`working_schedule_08`.`time_out` AS `time_out`,`hrone`.`working_schedule_08`.`plotter` AS `plotter`,`hrone`.`working_schedule_08`.`date_plotted` AS `date_plotted`,`hrone`.`working_schedule_08`.`restday` AS `restday`,`hrone`.`working_schedule_08`.`group_id` AS `group_id`,`hrone`.`employee_info`.`first_name` AS `first_name`,`hrone`.`employee_info`.`middle_name` AS `middle_name`,`hrone`.`employee_info`.`last_name` AS `last_name`,`hrone`.`employee_info`.`InActive` AS `InActive`,`hrone`.`company_info`.`company_name` AS `company_name`,`hrone`.`division`.`division_name` AS `division_name`,`hrone`.`department`.`dept_name` AS `dept_name`,`hrone`.`section`.`section_name` AS `section_name`,`hrone`.`subsection`.`subsection_name` AS `subsection_name`,`hrone`.`classification`.`classification` AS `classification`,`hrone`.`location`.`location_name` AS `location_name`,`hrone`.`employment`.`employment_name` AS `employment_name`,`hrone`.`employment`.`employment_id` AS `employment_id`,`hrone`.`division`.`division_id` AS `division_id`,`hrone`.`department`.`department_id` AS `department_id`,`hrone`.`section`.`section_id` AS `section_id`,`hrone`.`subsection`.`subsection_id` AS `subsection_id`,`hrone`.`classification`.`classification_id` AS `classification_id`,`hrone`.`location`.`location_id` AS `location_id` from (((((((((`hrone`.`working_schedule_08` join `hrone`.`employee_info` on((`hrone`.`employee_info`.`employee_id` = `hrone`.`working_schedule_08`.`employee_id`))) join `hrone`.`employment` on((`hrone`.`employment`.`employment_id` = `hrone`.`employee_info`.`employment`))) join `hrone`.`company_info` on((`hrone`.`company_info`.`company_id` = `hrone`.`employee_info`.`company_id`))) join `hrone`.`division` on((`hrone`.`division`.`division_id` = `hrone`.`employee_info`.`division_id`))) join `hrone`.`department` on((`hrone`.`department`.`department_id` = `hrone`.`employee_info`.`department`))) join `hrone`.`section` on((`hrone`.`section`.`section_id` = `hrone`.`employee_info`.`section`))) join `hrone`.`subsection` on((`hrone`.`subsection`.`subsection_id` = `hrone`.`employee_info`.`subsection`))) join `hrone`.`classification` on((`hrone`.`classification`.`classification_id` = `hrone`.`employee_info`.`classification`))) join `hrone`.`location` on((`hrone`.`location`.`location_id` = `hrone`.`employee_info`.`location`))) 



	 union 


	 select `hrone`.`working_schedule_09`.`id` AS `id`,`hrone`.`working_schedule_09`.`shift_id` AS `shift_id`,`hrone`.`working_schedule_09`.`date` AS `date`,`hrone`.`working_schedule_09`.`company_id` AS `company_id`,`hrone`.`working_schedule_09`.`employee_id` AS `employee_id`,`hrone`.`working_schedule_09`.`mm` AS `mm`,`hrone`.`working_schedule_09`.`yy` AS `yy`,`hrone`.`working_schedule_09`.`dd` AS `dd`,`hrone`.`working_schedule_09`.`shift_category` AS `shift_category`,`hrone`.`working_schedule_09`.`shift_in` AS `shift_in`,`hrone`.`working_schedule_09`.`shift_out` AS `shift_out`,`hrone`.`working_schedule_09`.`time_in` AS `time_in`,`hrone`.`working_schedule_09`.`time_out` AS `time_out`,`hrone`.`working_schedule_09`.`plotter` AS `plotter`,`hrone`.`working_schedule_09`.`date_plotted` AS `date_plotted`,`hrone`.`working_schedule_09`.`restday` AS `restday`,`hrone`.`working_schedule_09`.`group_id` AS `group_id`,`hrone`.`employee_info`.`first_name` AS `first_name`,`hrone`.`employee_info`.`middle_name` AS `middle_name`,`hrone`.`employee_info`.`last_name` AS `last_name`,`hrone`.`employee_info`.`InActive` AS `InActive`,`hrone`.`company_info`.`company_name` AS `company_name`,`hrone`.`division`.`division_name` AS `division_name`,`hrone`.`department`.`dept_name` AS `dept_name`,`hrone`.`section`.`section_name` AS `section_name`,`hrone`.`subsection`.`subsection_name` AS `subsection_name`,`hrone`.`classification`.`classification` AS `classification`,`hrone`.`location`.`location_name` AS `location_name`,`hrone`.`employment`.`employment_name` AS `employment_name`,`hrone`.`employment`.`employment_id` AS `employment_id`,`hrone`.`division`.`division_id` AS `division_id`,`hrone`.`department`.`department_id` AS `department_id`,`hrone`.`section`.`section_id` AS `section_id`,`hrone`.`subsection`.`subsection_id` AS `subsection_id`,`hrone`.`classification`.`classification_id` AS `classification_id`,`hrone`.`location`.`location_id` AS `location_id` from (((((((((`hrone`.`working_schedule_09` join `hrone`.`employee_info` on((`hrone`.`employee_info`.`employee_id` = `hrone`.`working_schedule_09`.`employee_id`))) join `hrone`.`employment` on((`hrone`.`employment`.`employment_id` = `hrone`.`employee_info`.`employment`))) join `hrone`.`company_info` on((`hrone`.`company_info`.`company_id` = `hrone`.`employee_info`.`company_id`))) join `hrone`.`division` on((`hrone`.`division`.`division_id` = `hrone`.`employee_info`.`division_id`))) join `hrone`.`department` on((`hrone`.`department`.`department_id` = `hrone`.`employee_info`.`department`))) join `hrone`.`section` on((`hrone`.`section`.`section_id` = `hrone`.`employee_info`.`section`))) join `hrone`.`subsection` on((`hrone`.`subsection`.`subsection_id` = `hrone`.`employee_info`.`subsection`))) join `hrone`.`classification` on((`hrone`.`classification`.`classification_id` = `hrone`.`employee_info`.`classification`))) join `hrone`.`location` on((`hrone`.`location`.`location_id` = `hrone`.`employee_info`.`location`))) 



	 union 


	 select `hrone`.`working_schedule_10`.`id` AS `id`,`hrone`.`working_schedule_10`.`shift_id` AS `shift_id`,`hrone`.`working_schedule_10`.`date` AS `date`,`hrone`.`working_schedule_10`.`company_id` AS `company_id`,`hrone`.`working_schedule_10`.`employee_id` AS `employee_id`,`hrone`.`working_schedule_10`.`mm` AS `mm`,`hrone`.`working_schedule_10`.`yy` AS `yy`,`hrone`.`working_schedule_10`.`dd` AS `dd`,`hrone`.`working_schedule_10`.`shift_category` AS `shift_category`,`hrone`.`working_schedule_10`.`shift_in` AS `shift_in`,`hrone`.`working_schedule_10`.`shift_out` AS `shift_out`,`hrone`.`working_schedule_10`.`time_in` AS `time_in`,`hrone`.`working_schedule_10`.`time_out` AS `time_out`,`hrone`.`working_schedule_10`.`plotter` AS `plotter`,`hrone`.`working_schedule_10`.`date_plotted` AS `date_plotted`,`hrone`.`working_schedule_10`.`restday` AS `restday`,`hrone`.`working_schedule_10`.`group_id` AS `group_id`,`hrone`.`employee_info`.`first_name` AS `first_name`,`hrone`.`employee_info`.`middle_name` AS `middle_name`,`hrone`.`employee_info`.`last_name` AS `last_name`,`hrone`.`employee_info`.`InActive` AS `InActive`,`hrone`.`company_info`.`company_name` AS `company_name`,`hrone`.`division`.`division_name` AS `division_name`,`hrone`.`department`.`dept_name` AS `dept_name`,`hrone`.`section`.`section_name` AS `section_name`,`hrone`.`subsection`.`subsection_name` AS `subsection_name`,`hrone`.`classification`.`classification` AS `classification`,`hrone`.`location`.`location_name` AS `location_name`,`hrone`.`employment`.`employment_name` AS `employment_name`,`hrone`.`employment`.`employment_id` AS `employment_id`,`hrone`.`division`.`division_id` AS `division_id`,`hrone`.`department`.`department_id` AS `department_id`,`hrone`.`section`.`section_id` AS `section_id`,`hrone`.`subsection`.`subsection_id` AS `subsection_id`,`hrone`.`classification`.`classification_id` AS `classification_id`,`hrone`.`location`.`location_id` AS `location_id` from (((((((((`hrone`.`working_schedule_10` join `hrone`.`employee_info` on((`hrone`.`employee_info`.`employee_id` = `hrone`.`working_schedule_10`.`employee_id`))) join `hrone`.`employment` on((`hrone`.`employment`.`employment_id` = `hrone`.`employee_info`.`employment`))) join `hrone`.`company_info` on((`hrone`.`company_info`.`company_id` = `hrone`.`employee_info`.`company_id`))) join `hrone`.`division` on((`hrone`.`division`.`division_id` = `hrone`.`employee_info`.`division_id`))) join `hrone`.`department` on((`hrone`.`department`.`department_id` = `hrone`.`employee_info`.`department`))) join `hrone`.`section` on((`hrone`.`section`.`section_id` = `hrone`.`employee_info`.`section`))) join `hrone`.`subsection` on((`hrone`.`subsection`.`subsection_id` = `hrone`.`employee_info`.`subsection`))) join `hrone`.`classification` on((`hrone`.`classification`.`classification_id` = `hrone`.`employee_info`.`classification`))) join `hrone`.`location` on((`hrone`.`location`.`location_id` = `hrone`.`employee_info`.`location`))) 

	 union




	  select `hrone`.`working_schedule_11`.`id` AS `id`,`hrone`.`working_schedule_11`.`shift_id` AS `shift_id`,`hrone`.`working_schedule_11`.`date` AS `date`,`hrone`.`working_schedule_11`.`company_id` AS `company_id`,`hrone`.`working_schedule_11`.`employee_id` AS `employee_id`,`hrone`.`working_schedule_11`.`mm` AS `mm`,`hrone`.`working_schedule_11`.`yy` AS `yy`,`hrone`.`working_schedule_11`.`dd` AS `dd`,`hrone`.`working_schedule_11`.`shift_category` AS `shift_category`,`hrone`.`working_schedule_11`.`shift_in` AS `shift_in`,`hrone`.`working_schedule_11`.`shift_out` AS `shift_out`,`hrone`.`working_schedule_11`.`time_in` AS `time_in`,`hrone`.`working_schedule_11`.`time_out` AS `time_out`,`hrone`.`working_schedule_11`.`plotter` AS `plotter`,`hrone`.`working_schedule_11`.`date_plotted` AS `date_plotted`,`hrone`.`working_schedule_11`.`restday` AS `restday`,`hrone`.`working_schedule_11`.`group_id` AS `group_id`,`hrone`.`employee_info`.`first_name` AS `first_name`,`hrone`.`employee_info`.`middle_name` AS `middle_name`,`hrone`.`employee_info`.`last_name` AS `last_name`,`hrone`.`employee_info`.`InActive` AS `InActive`,`hrone`.`company_info`.`company_name` AS `company_name`,`hrone`.`division`.`division_name` AS `division_name`,`hrone`.`department`.`dept_name` AS `dept_name`,`hrone`.`section`.`section_name` AS `section_name`,`hrone`.`subsection`.`subsection_name` AS `subsection_name`,`hrone`.`classification`.`classification` AS `classification`,`hrone`.`location`.`location_name` AS `location_name`,`hrone`.`employment`.`employment_name` AS `employment_name`,`hrone`.`employment`.`employment_id` AS `employment_id`,`hrone`.`division`.`division_id` AS `division_id`,`hrone`.`department`.`department_id` AS `department_id`,`hrone`.`section`.`section_id` AS `section_id`,`hrone`.`subsection`.`subsection_id` AS `subsection_id`,`hrone`.`classification`.`classification_id` AS `classification_id`,`hrone`.`location`.`location_id` AS `location_id` from (((((((((`hrone`.`working_schedule_11` join `hrone`.`employee_info` on((`hrone`.`employee_info`.`employee_id` = `hrone`.`working_schedule_11`.`employee_id`))) join `hrone`.`employment` on((`hrone`.`employment`.`employment_id` = `hrone`.`employee_info`.`employment`))) join `hrone`.`company_info` on((`hrone`.`company_info`.`company_id` = `hrone`.`employee_info`.`company_id`))) join `hrone`.`division` on((`hrone`.`division`.`division_id` = `hrone`.`employee_info`.`division_id`))) join `hrone`.`department` on((`hrone`.`department`.`department_id` = `hrone`.`employee_info`.`department`))) join `hrone`.`section` on((`hrone`.`section`.`section_id` = `hrone`.`employee_info`.`section`))) join `hrone`.`subsection` on((`hrone`.`subsection`.`subsection_id` = `hrone`.`employee_info`.`subsection`))) join `hrone`.`classification` on((`hrone`.`classification`.`classification_id` = `hrone`.`employee_info`.`classification`))) join `hrone`.`location` on((`hrone`.`location`.`location_id` = `hrone`.`employee_info`.`location`))) 


	  union




	   select `hrone`.`working_schedule_12`.`id` AS `id`,`hrone`.`working_schedule_12`.`shift_id` AS `shift_id`,`hrone`.`working_schedule_12`.`date` AS `date`,`hrone`.`working_schedule_12`.`company_id` AS `company_id`,`hrone`.`working_schedule_12`.`employee_id` AS `employee_id`,`hrone`.`working_schedule_12`.`mm` AS `mm`,`hrone`.`working_schedule_12`.`yy` AS `yy`,`hrone`.`working_schedule_12`.`dd` AS `dd`,`hrone`.`working_schedule_12`.`shift_category` AS `shift_category`,`hrone`.`working_schedule_12`.`shift_in` AS `shift_in`,`hrone`.`working_schedule_12`.`shift_out` AS `shift_out`,`hrone`.`working_schedule_12`.`time_in` AS `time_in`,`hrone`.`working_schedule_12`.`time_out` AS `time_out`,`hrone`.`working_schedule_12`.`plotter` AS `plotter`,`hrone`.`working_schedule_12`.`date_plotted` AS `date_plotted`,`hrone`.`working_schedule_12`.`restday` AS `restday`,`hrone`.`working_schedule_12`.`group_id` AS `group_id`,`hrone`.`employee_info`.`first_name` AS `first_name`,`hrone`.`employee_info`.`middle_name` AS `middle_name`,`hrone`.`employee_info`.`last_name` AS `last_name`,`hrone`.`employee_info`.`InActive` AS `InActive`,`hrone`.`company_info`.`company_name` AS `company_name`,`hrone`.`division`.`division_name` AS `division_name`,`hrone`.`department`.`dept_name` AS `dept_name`,`hrone`.`section`.`section_name` AS `section_name`,`hrone`.`subsection`.`subsection_name` AS `subsection_name`,`hrone`.`classification`.`classification` AS `classification`,`hrone`.`location`.`location_name` AS `location_name`,`hrone`.`employment`.`employment_name` AS `employment_name`,`hrone`.`employment`.`employment_id` AS `employment_id`,`hrone`.`division`.`division_id` AS `division_id`,`hrone`.`department`.`department_id` AS `department_id`,`hrone`.`section`.`section_id` AS `section_id`,`hrone`.`subsection`.`subsection_id` AS `subsection_id`,`hrone`.`classification`.`classification_id` AS `classification_id`,`hrone`.`location`.`location_id` AS `location_id` from (((((((((`hrone`.`working_schedule_12` join `hrone`.`employee_info` on((`hrone`.`employee_info`.`employee_id` = `hrone`.`working_schedule_12`.`employee_id`))) join `hrone`.`employment` on((`hrone`.`employment`.`employment_id` = `hrone`.`employee_info`.`employment`))) join `hrone`.`company_info` on((`hrone`.`company_info`.`company_id` = `hrone`.`employee_info`.`company_id`))) join `hrone`.`division` on((`hrone`.`division`.`division_id` = `hrone`.`employee_info`.`division_id`))) join `hrone`.`department` on((`hrone`.`department`.`department_id` = `hrone`.`employee_info`.`department`))) join `hrone`.`section` on((`hrone`.`section`.`section_id` = `hrone`.`employee_info`.`section`))) join `hrone`.`subsection` on((`hrone`.`subsection`.`subsection_id` = `hrone`.`employee_info`.`subsection`))) join `hrone`.`classification` on((`hrone`.`classification`.`classification_id` = `hrone`.`employee_info`.`classification`))) join `hrone`.`location` on((`hrone`.`location`.`location_id` = `hrone`.`employee_info`.`location`)))) `x`

